# Generated by Django 4.0 on 2023-05-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300)),
                ('tuman', models.TextField(choices=[('Chortoq tumani', 'Chortoq Tumani'), ('Chust tumani', 'Chust Tumani'), ('Kosonsoy tumani', 'Kosonsoy Tumani'), ('Mingbuloq tumani', 'Mingbuloq Tumani'), ('Namangan tumani', 'Namangan Tumani'), ('Norin tumani', 'Norin Tumani'), ('Pop tumani', 'Pop Tumani'), ("To'raqo'rg'on tumani", 'Turaqurgon Tumani'), ("Uchqo'rg'on tumani", 'Uchkurgan Tumani'), ('Uychi tumani', 'Uychi Tumani'), ("Yangiqo'rg'on tumani", 'Yangikurgan Tumani'), ('Davlatobod tumani', 'Davlatobod Tumani'), ('Yangi Namangan tumani', 'Yangi Namangan'), ('Namangan shahri', 'Namangan Shaxri')], default='Namangan shahri', max_length=100)),
                ('ishchilar_soni', models.PositiveIntegerField()),
                ('telefon', models.CharField(max_length=30)),
                ('yotoq_joyi', models.CharField(choices=[('Mavjud', 'Mavjud'), ('Mavjud emas', 'Mavjud Emas')], default='mavjud', max_length=100)),
                ('ish_vaqti', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='contact.jpg', upload_to='hospitals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=120)),
                ('familiya', models.CharField(max_length=120)),
                ('telefon', models.CharField(max_length=30)),
                ('korik_narxi', models.DecimalField(decimal_places=2, max_digits=16)),
                ('photo', models.ImageField(default='doctor.jpg', upload_to='doctors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ish_vaqti', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.categories')),
                ('shifoxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospitals')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='shifoxona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hospital.hospitals'),
        ),
    ]
