# Generated by Django 4.0 on 2023-05-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(default='media/doctor.jpg', upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='photo',
            field=models.ImageField(default='media/contact.jpg', upload_to='hospitals/'),
        ),
    ]
