# Generated by Django 4.0 on 2023-05-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctors_photo_alter_hospitals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(default='doctor.jpg', upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='photo',
            field=models.ImageField(default='contact.jpg', upload_to='hospitals/'),
        ),
    ]
