# Generated by Django 4.0 on 2023-05-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctors_photo_alter_hospitals_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=120)),
                ('telefon', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
